common:
  port: 8080
postgres:
  database: postgres
  user: postgres
  password: postgres
  host: localhost
  port: 5432
  require_ssl: false
hashlib:
  hash_name: sha256
  salt: rfrfz-nj cjkm
  iterations: 100000
jwt:
  secret: wgW?9A#?
  algorithm: HS256
  exp_min: 30
  exp_days: 30
