common:
  port: 8080
postgres:
  database: postgres
  user: postgres
  password: postgres
  host: localhost
  port: 5432
  require_ssl: false
hashlib:
  hash_name: sha256
  salt: rfrfz-nj cjkm
  iterations: 100000
